### PR TITLE
fixed `abbreviateField` for case when value is empty string

### PR DESCRIPTION
**Pull request by vancleve**

### CODE REVIEW

**Comment by vancleve** [comment]
@jlegewie: simple fix for the `abbreviateField` function that I added a little while ago.

**Comment by vancleve** [comment]
Sorry to bump this @jlegewie, its just a quick fix to the the `abbreviateField` we added awhile back.

**Comment by jlegewie** [comment]
Done. Will push a new version over the next days with a couple of fixes from pull requests.

Generally, my challenge with the PRs is that testing the change takes by far the most time. Mentioning the amount of testing and behavior with different input would help in these circumstances. This PR, for example, is simple but I don't know without testing and research when the function returns "" and whether that makes the most sense.

**Comment by vancleve** [comment]
right, got it! I'll put more detail in next time!

**Pull request merged**
