### PR TITLE
Solving the bug of group-renaming in-place

### PR DESCRIPTION
**Pull request by sohamm17**

### CODE REVIEW

**Comment by sohamm17** [comment]
I think I am not doing it in some wrong way. However, I would say that for "b16a308" (https://github.com/sohamm17/zotfile/commit/b16a30855f93517455791abd37389ea5cedb6400) this commit, the lines added from 1912 to 1919 should be merged to solve the problem.

**Comment by jlegewie** [comment]
Thanks! I think I merged the relevant part...

**Comment by sohamm17** [comment]
Okay. Can you please let me know if this is correct process to submit a pull request or not?

**Comment by jlegewie** [comment]
I am far from a git expert so take everything I say with a grain of salt. In principle that is how you submit a pull request. Usually, you would only include the relevant changes though and exclude others. Creating a feature branch that only includes the changes relevant for a particular feature or bug fix would probably be the way to go (you can find some info when you google "feature branch"). The other thing that made it hard for me to merge directly (I ended up manually copying the changes) is that your code formatting seems to be off. The part that starts with `if(destination.trim() == this.folderSep) {` in b16a308 is intended incorrectly. The same is true for the later part that includes the `alert(filename);` (which you removed in a later commit, I think). The code is completely out of line in your version. If you want to send a pull request to Zotero, they would also ask you to consistently use their indentation method (I forgot whether they use spaces or tabs) and they would ask you to squash commits (just google squash to find out more). But keep in mind that I am struggling with git from time to time myself...    :)

**Pull request closed without merging**
