### PR TITLE
add CollectionPath(using wildcard %c) support for subfolder format.

### PR DESCRIPTION
**Pull request by simpzan**
- usually, items in zotero are organized in collection paths. I think it is natural to organize attachments similarly in filesystem. 
- but the problem is that one item can be in more than one collection paths, while one attachment can only in one folder. 
- a simple solution is just to prompt user to select a collection path as subfolder of the attachment.

### CODE REVIEW

**Comment by cmf84** [comment]
First of all, thank you very much for this extremely useful feature.

However, there seems to be a problem with the collection path subfolders. The resulting folder structure is inconsistent between operating systems:
On a Mac, some item in the collection projects/papers will get moved to a subfolder `projects/papers`.
On a Windows machine, the item instead ends up in `projectspapers/` 
Perhaps the code doesn't handle the Windows forward-slash properly?

**Comment by jlegewie** [comment]
Are you talking about the `%c` wildcard used with the option "Use additional subfolders..."?

I don't have a windows PC so it's pretty hard to test windows-related stuff...

**Comment by cmf84** [comment]
Yes, sorry not to mention that. I am talking about the %c wildcard in the subfolder-field, to organize the item-files into a meaningful folder structure.

If it's just about testing the fix on a windows machine, I could do that..

**Comment by jlegewie** [comment]
I briefly looked but wasn't able to figure it out right away. So it might take a little. Can you open a separate issue that includes the same details posted here? Thanks!

**Comment by cmf84** [comment]
Sure, I just opened a new issue for this.

**Pull request merged**
