### PR TITLE
Fix #197 and #184

### LINKED ISSUE #197: Delete folder(s) if no last file is moved out
I frequently store entries with corresponding PDF or other documents before assigning to a given collection. This means they stay in "Unfiled items" and will have a corresponding "undefined/" location on disk.
Later on I reassign the entry to a given collection and hit "Rename attachments" to force the file to move to a new folder matching the new collection. This works fine however the folder hierarchy created under "undefined/..." is, after a while, left full of empty folders.

Could zotfile remove these folders and any parent in the hierarchy when the last file is moved or removed out of it (i.e. when the folder first becomes empty)?

### PR DESCRIPTION
**Pull request by Unode**
- Remove empty folders when last file is moved
- Prevent double // in paths introduced by the user

### CODE REVIEW

**Comment by jlegewie** [comment]
Are you sure that this is a desirable behavior for all calls to `moveFile`? What if the file is in `~/Downloads` or other important folders? Maybe I am missing something...

By the way, I really appreciate the bug fixing! I don't find a lot of time to look at these issue right now myself.

**Comment by Unode** [comment]
I'm not sure i covered all the cases and I might have understood something wrong. I assumed files could only be stored in one of two locations, the zotero internal folder (in firefox profile) and a custom storage location specified in zotfile settings.

In these two locations I tested the code and it worked as intended. That is removing only empty folders or those containing only hidden files.

In the case of `~/Downloads`, would this be stored in zotero as a link to a file? I'm not familiar with this functionality. Perhaps a safer option is to test if the original path starts with either the zotfile location or firefox profile location and only remove folders if this is the case. I'll patch it like that.

**Comment by Unode** [comment]
Could you test that it works? I'm not sure how to create an entry that would be stored in `~/Downloads`.

Thanks

**Comment by jlegewie** [comment]
Zotfile only allows for these two storage options but here are two scenarios:
1) Someone changes the custom storage location. 
2) You can use zotero itself to add linked attachments from any location. So a user could manually add a linked attachments with zotero and then rename with zotfile (or the user just installed zotfile and the existing attachments are in some location). I think `removeEmptyFolders` would be called with that location.

I will test on the weekend to further investigate.

**Comment by Unode** [comment]
Hi again Joscha,

So I was playing a little with the code and the settings over the weekend trying to evaluate the impact of the patch. With both 1) and 2), the original folder is left empty or untouched.

As for something that works in all situations... Everything I tried always ended up with scenarios were trying to remove empty folders recursively would accidentally remove parents of the folder or leave part of the folders behind. The only solution would be to keep track of the original custom location and custom subfolder per-item which is highly impractical.

With that said, the current is the best "compromise" solution I can come up with.

**Comment by jlegewie** [comment]
Perfect, thanks! I just tried myself and everything is working. I missed the `f.path.startsWith()` part, which takes care of the two scenarios I described.

Are you planing any other fixes?

**Comment by Unode** [comment]
If I bump into more things that make me itchy I'll scratch them.
For now I think all the major ones are done so release away ;).

**Comment by jlegewie** [comment]
Okay, thanks! I will wait on a bug report from the forum and otherwise submit to mozilla.

**Pull request merged**
