### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by wohenbushuang**

### CODE REVIEW

**Comment by qqobb** [comment]
@wohenbushuang: See https://github.com/jlegewie/zotfile/pull/330 for related work. It seems that releases with a Chinese locale can be found here: https://github.com/lychichem/zotfile/releases

See also https://github.com/jlegewie/zotfile/issues/522#issuecomment-806630585:
>The unfortunate answer is that I won't have any time to invest in the development in the foreseeable future.

**Comment by wohenbushuang** [comment]
> @wohenbushuang: See #330 for related work. It seems that releases with a Chinese locale can be found here: https://github.com/lychichem/zotfile/releases

Sadly #330 have been closed without merging, though the forked repo is still updating to the latest version during these years. It can hardly be found since the "forked" repo is not searchable on github, unless people know the exact link address, or the forked repo's owner chooses to create a new, independent clone.

@qqobb Thanks for expaining why this PR doesn't have any news during these months. In fact, I still wish that @jlegewie can spend a little time to just merge the translation files without development need, for the convenience that Chinese users can directly use and no need to find out the translations like #330 or mine. As I mentioned in #568,
> hope that there will be more people that use Chinses can use this plugin for convenience.

**Comment by wohenbushuang** [comment]
@qqobb Okay I read the mentioned links furthermore, and notice that #330 was created in 2018 and recieves no feedbacks so far. Actually if it has been merged or even replied in these years, I won't need to translate again myself and all people will enjoy the translation out-of-box.

**Comment by lychichem** [comment]
> > @wohenbushuang: See #330 for related work. It seems that releases with a Chinese locale can be found here: https://github.com/lychichem/zotfile/releases
> 
> Sadly #330 have been closed without merging, though the forked repo is still updating to the latest version during these years. It can hardly be found since the "forked" repo is not searchable on github, unless people know the exact link address, or the forked repo's owner chooses to create a new, independent clone.
> 
> @qqobb Thanks for expaining why this PR doesn't have any news during these months. In fact, I still wish that @jlegewie can spend a little time to just merge the translation files without development need, for the convenience that Chinese users can directly use and no need to find out the translations like #330 or mine. As I mentioned in #568,
> 
> > hope that there will be more people that use Chinses can use this plugin for convenience.

As the author for PR #330 , I have to say, closing this is a mistake. I once noticed the repo takes significantly larger space on my hard disk, and I searched and believed that cleaning all the history will make it slim. So I rebased my repo. As a result, the PR was force closed.
However, I don't know why my PR haven't been merged for a long time. Maybe just as Joscha Legewie said, he has no enough time to take care of all the requests.

**Comment by wohenbushuang** [comment]
1. this repo has no updates for years
2. I have moved to file-sync app for an easier life

**Pull request closed without merging**
