### PR TITLE
Add senior (last) author wildcards

### PR DESCRIPTION
**Pull request by bwiernik**
Requested here:
https://forums.zotero.org/discussion/51157/sorting-by-last-author/#Comment_240817

### CODE REVIEW

**Comment by jlegewie** [comment]
Thanks! What do you think about calling this `lastAuthor` and not `seniorAuthor`? In many disciplines, the last author is not necessarily the senior author so that the name is a little misleading.

**Comment by bwiernik** [comment]
I changed the variables to lastAuthor

**Comment by jlegewie** [comment]
Thanks!

**Comment by Unode** [comment]
This has been merged but could you have a look at #208 .
The patch seems to be incomplete or refers to functionality not valid in the latest Zotero release (stable).

**Comment by ajasja** [comment]
@jlegewie Not sure if I should open a new issue, but `%q` is not documented on the main webpage.
That's a real shame, since it took me two days to find:)

**Pull request merged**
